// mark as a module for TypeScript
import "./declare-props"

declare global {
  namespace JSX {
    interface IntrinsicElements {
      a: HtmlAnchorProps
      abbr: HtmlProps<HTMLElement>
      address: HtmlProps<HTMLElement>
      area: HtmlAreaProps
      article: HtmlProps<HTMLElement>
      aside: HtmlProps<HTMLElement>
      audio: HtmlAudioProps
      b: HtmlProps<HTMLElement>
      base: HtmlBaseProps
      bdi: HtmlProps<HTMLElement>
      bdo: HtmlProps<HTMLElement>
      blockquote: HtmlQuoteProps
      body: HtmlBodyProps
      br: HtmlProps<HTMLElement>
      button: HtmlButtonProps
      canvas: HtmlCanvasProps
      caption: HtmlProps<HTMLElement>
      cite: HtmlProps<HTMLElement>
      code: HtmlProps<HTMLElement>
      col: HtmlTableColProps
      colgroup: HtmlTableColProps
      data: HtmlDataProps
      datalist: HtmlDataListProps
      dd: HtmlProps<HTMLElement>
      del: HtmlModProps
      details: HtmlDetailsProps
      dfn: HtmlProps<HTMLElement>
      div: HtmlProps<HTMLDivElement>
      dl: HtmlProps<HTMLElement>
      dt: HtmlProps<HTMLElement>
      em: HtmlProps<HTMLElement>
      embed: HtmlEmbedProps
      fieldset: HtmlFieldSetProps
      figcaption: HtmlProps<HTMLElement>
      figure: HtmlProps<HTMLElement>
      footer: HtmlProps<HTMLElement>
      form: HtmlFormProps
      h1: HtmlProps<HTMLElement>
      h2: HtmlProps<HTMLElement>
      h3: HtmlProps<HTMLElement>
      h4: HtmlProps<HTMLElement>
      h5: HtmlProps<HTMLElement>
      h6: HtmlProps<HTMLElement>
      head: HtmlProps<HTMLElement>
      header: HtmlProps<HTMLElement>
      hr: HtmlProps<HTMLElement>
      html: HtmlHtmlProps
      i: HtmlProps<HTMLElement>
      iframe: HtmlIFrameProps
      img: HtmlImageProps
      input: HtmlInputProps
      ins: HtmlModProps
      kbd: HtmlProps<HTMLElement>
      label: HtmlLabelProps
      legend: HtmlLegendProps
      li: HtmlLIProps
      link: HtmlLinkProps
      main: HtmlProps<HTMLElement>
      map: HtmlMapProps
      mark: HtmlProps<HTMLElement>
      menu: HtmlMenuProps
      meta: HtmlMetaProps
      meter: HtmlMeterProps
      nav: HtmlProps<HTMLElement>
      noscript: HtmlProps<HTMLElement>
      object: HtmlObjectProps
      ol: HtmlOListProps
      optgroup: HtmlOptGroupProps
      option: HtmlOptionProps
      output: HtmlOutputProps
      p: HtmlProps<HTMLElement>
      param: HtmlParamProps
      pre: HtmlProps<HTMLElement>
      progress: HtmlProgressProps
      q: HtmlQuoteProps
      rb: HtmlProps<HTMLElement>
      rp: HtmlProps<HTMLElement>
      rt: HtmlProps<HTMLElement>
      rtc: HtmlProps<HTMLElement>
      ruby: HtmlProps<HTMLElement>
      s: HtmlProps<HTMLElement>
      samp: HtmlProps<HTMLElement>
      script: HtmlScriptProps
      section: HtmlProps<HTMLElement>
      select: HtmlSelectProps
      small: HtmlProps<HTMLElement>
      source: HtmlSourceProps
      span: HtmlProps<HTMLElement>
      strong: HtmlProps<HTMLElement>
      style: HtmlStyleProps
      sub: HtmlProps<HTMLElement>
      sup: HtmlProps<HTMLElement>
      table: HtmlTableProps
      tbody: HtmlProps<HTMLElement>
      td: HtmlTableDataCellProps
      template: HtmlProps<HTMLElement>
      textarea: HtmlTextAreaProps
      tfoot: HtmlTableSectionProps
      th: HtmlTableHeaderCellProps
      thead: HtmlTableSectionProps
      time: HtmlTimeProps
      title: HtmlProps<HTMLElement>
      tr: HtmlTableRowProps
      track: HtmlTrackProps
      u: HtmlProps<HTMLElement>
      ul: HtmlProps<HTMLElement>
      var: HtmlProps<HTMLElement>
      video: HtmlVideoProps
      wbr: HtmlProps<HTMLElement>
    }
  }
}
